_target_: src.models.token_tagging_regressor.TokenTaggingRegressor

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
  
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

huggingface_model: gpt2
num_labels: 1

mlp:
  use: False 
